modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/satyrnidae/lepidopterapi"
license = "MIT"

[[mods]]
modId = "lepidoptera_api"
version = "${version}"
displayName = "Lepidoptera API"
authors = "satyrnidae"
description = '''
Provides common functionality for satyrnidae's mods.
'''
#logoFile = ""

[[dependencies.lepidoptera_api]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lepidoptera_api]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lepidoptera_api]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.lepidoptera_api]]
modId = "cloth_config"
mandatory = false
versionRange = "[8.3.134,)"
ordering = "NONE"
side = "BOTH"
